[package]
name = "romhack-wasm"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[lib]
name = "romhack"
crate-type = ["cdylib"]

[dependencies]
romhack-backend = { path = "../backend" }
wii-crypto = { path = "../wii-crypto" }
failure = "0.1.2"
wasm-bindgen = "0.2"
