[package]
name = "romhack-patcher"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
iui = { git = "https://github.com/rust-native-ui/libui-rs.git", branch="trunk" }
romhack-backend = { path = "../backend" }
